ci: add deno check (#439)

diff --git a/.github/workflows/deno.yml b/.github/workflows/deno.yml
--- a/.github/workflows/deno.yml
+++ b/.github/workflows/deno.yml
@@ -18,7 +18,7 @@ jobs:
       - name: Format
         run: deno task format:check
 
-  lint:
+  check:
     runs-on: ubuntu-20.04
     timeout-minutes: 2
     steps:
@@ -29,5 +29,18 @@ jobs:
         with:
           deno-version: "1.41.1"
 
+      - name: Build Artifacts
+        run: |
+          deno task artifacts:build
+
+          if ! git diff --exit-code || ! git diff --staged --exit-code; then
+            echo "Error: Genreated artifacts are not up to date."
+            exit 1
+          fi
+
+      - name: Check
+        run: deno task check:dirty
+
       - name: Lint
-        run: deno task lint
+        run: deno task lint:dirty
+
